/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Authentication/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Validates user credentials and issues JWT + refresh tokens inside HttpOnly cookies.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Authentication/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Authentication/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current authenticated user
         * @description Returns UserDto containing user ID, email, roles, and allowed warehouse IDs.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information retrieved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description User is not authenticated. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Authentication/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Uses refresh cookie to generate a new access token and rotate refresh token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tokens refreshed successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Refresh token invalid or missing. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Authentication/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterCommand"];
                    "text/json": components["schemas"]["RegisterCommand"];
                    "application/*+json": components["schemas"]["RegisterCommand"];
                };
            };
            responses: {
                /** @description User registered successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisterResponse"];
                        "application/json": components["schemas"]["RegisterResponse"];
                        "text/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Email already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Forecasting/warehouse/{warehouseId}/item/{itemId}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest forecast for item */
        get: {
            parameters: {
                query?: {
                    horizonDays?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forecast returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ForecastSeriesDto"];
                        "application/json": components["schemas"]["ForecastSeriesDto"];
                        "text/json": components["schemas"]["ForecastSeriesDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Forecasting/warehouse/{warehouseId}/item/{itemId}/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Train forecast for item
         * @description Trains an SSA-based demand forecast for the given warehouse and item.
         */
        post: {
            parameters: {
                query?: {
                    horizonDays?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Forecast series created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ForecastSeriesDto"];
                        "application/json": components["schemas"]["ForecastSeriesDto"];
                        "text/json": components["schemas"]["ForecastSeriesDto"];
                    };
                };
                /** @description User not allowed to access this warehouse. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No shipment history for this item. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Forecasting/warehouse/{warehouseId}/train-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Train forecasts for all warehouse items
         * @description Aggregates shipment history for every item in a warehouse and trains SSA forecasts.
         */
        post: {
            parameters: {
                query?: {
                    horizonDays?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Training completed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TrainForecastResultDto"];
                        "application/json": components["schemas"]["TrainForecastResultDto"];
                        "text/json": components["schemas"]["TrainForecastResultDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns basic operational status of the Magna WMS API.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The API is healthy. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                        "application/json": unknown;
                        "text/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Health/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping test
         * @description Simple connectivity test endpoint. Returns 'pong' if reachable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API connectivity confirmed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Verifies DB connectivity and overall API readiness.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Application and database are ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": unknown;
                        "application/json": unknown;
                        "text/json": unknown;
                    };
                };
                /** @description Database unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get inventory
         * @description Returns inventory across allowed warehouses. Optionally filter by warehouse ID.
         */
        get: {
            parameters: {
                query?: {
                    warehouseId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory retrieved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InventoryDto"][];
                        "application/json": components["schemas"]["InventoryDto"][];
                        "text/json": components["schemas"]["InventoryDto"][];
                    };
                };
                /** @description User is not allowed to access requested warehouse. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Inventory/{warehouseId}/items/{itemId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get inventory ledger for item
         * @description Returns inventory ledger entries for a specific item in a warehouse. Optionally filter by location.
         */
        get: {
            parameters: {
                query?: {
                    locationId?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ledger entries returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InventoryLedgerEntryDto"][];
                        "application/json": components["schemas"]["InventoryLedgerEntryDto"][];
                        "text/json": components["schemas"]["InventoryLedgerEntryDto"][];
                    };
                };
                /** @description User is not allowed to access requested warehouse. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all items
         * @description Returns all items currently registered in the system.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of items returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ItemDto"][];
                        "application/json": components["schemas"]["ItemDto"][];
                        "text/json": components["schemas"]["ItemDto"][];
                    };
                };
                /** @description No items found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Location/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get locations by Warehouse ID
         * @description Returns all locations assigned to the specified warehouse.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of locations returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LocationDto"][];
                        "application/json": components["schemas"]["LocationDto"][];
                        "text/json": components["schemas"]["LocationDto"][];
                    };
                };
                /** @description No locations found for the given warehouse. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Permission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all permissions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Permissions retrieved successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PermissionDto"][];
                        "application/json": components["schemas"]["PermissionDto"][];
                        "text/json": components["schemas"]["PermissionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PickTask/{taskId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pick task */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickTaskDto"];
                        "application/json": components["schemas"]["PickTaskDto"];
                        "text/json": components["schemas"]["PickTaskDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PickTask/{taskId}/lines/{lineId}/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pick item for a task line */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: number;
                    lineId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PickItemRequest"];
                    "text/json": components["schemas"]["PickItemRequest"];
                    "application/*+json": components["schemas"]["PickItemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickTaskDto"];
                        "application/json": components["schemas"]["PickTaskDto"];
                        "text/json": components["schemas"]["PickTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PickTask/{taskId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start pick task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickTaskDto"];
                        "application/json": components["schemas"]["PickTaskDto"];
                        "text/json": components["schemas"]["PickTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PickTask/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create pick task */
        post: {
            parameters: {
                query?: {
                    salesOrderId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickTaskDto"];
                        "application/json": components["schemas"]["PickTaskDto"];
                        "text/json": components["schemas"]["PickTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/PickTask/warehouse/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pick tasks by warehouse */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PickTaskDto"][];
                        "application/json": components["schemas"]["PickTaskDto"][];
                        "text/json": components["schemas"]["PickTaskDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Putaway/task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new putaway task. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePutawayTaskRequest"];
                    "text/json": components["schemas"]["CreatePutawayTaskRequest"];
                    "application/*+json": components["schemas"]["CreatePutawayTaskRequest"];
                };
            };
            responses: {
                /** @description Putaway task created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PutawayTaskDto"];
                        "application/json": components["schemas"]["PutawayTaskDto"];
                        "text/json": components["schemas"]["PutawayTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Putaway/task/{taskId}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute an existing putaway task (move stock to final location). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    taskId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ExecutePutawayRequest"];
                    "text/json": components["schemas"]["ExecutePutawayRequest"];
                    "application/*+json": components["schemas"]["ExecutePutawayRequest"];
                };
            };
            responses: {
                /** @description Putaway executed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PutawayTaskDto"];
                        "application/json": components["schemas"]["PutawayTaskDto"];
                        "text/json": components["schemas"]["PutawayTaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new receipt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateReceiptRequest"];
                    "text/json": components["schemas"]["CreateReceiptRequest"];
                    "application/*+json": components["schemas"]["CreateReceiptRequest"];
                };
            };
            responses: {
                /** @description Receipt created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiptDto"];
                        "application/json": components["schemas"]["ReceiptDto"];
                        "text/json": components["schemas"]["ReceiptDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Receipt/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get receipt by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipt returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiptDto"];
                        "application/json": components["schemas"]["ReceiptDto"];
                        "text/json": components["schemas"]["ReceiptDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Receipt/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get receipt lines for a receipt */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipt lines returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiptLineDto"][];
                        "application/json": components["schemas"]["ReceiptLineDto"][];
                        "text/json": components["schemas"]["ReceiptLineDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Receipt/{id}/lines/{lineId}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive quantity for a receipt line */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    lineId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReceiveReceiptLineRequest"];
                    "text/json": components["schemas"]["ReceiveReceiptLineRequest"];
                    "application/*+json": components["schemas"]["ReceiveReceiptLineRequest"];
                };
            };
            responses: {
                /** @description Receipt updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiptDto"];
                        "application/json": components["schemas"]["ReceiptDto"];
                        "text/json": components["schemas"]["ReceiptDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Receipt/warehouse/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all receipts for a warehouse */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipts returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReceiptDto"][];
                        "application/json": components["schemas"]["ReceiptDto"][];
                        "text/json": components["schemas"]["ReceiptDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Replenishment/warehouse/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get replenishment suggestions for all warehouse items */
        get: {
            parameters: {
                query?: {
                    horizonDays?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestions returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReplenishmentSuggestionDto"][];
                        "application/json": components["schemas"]["ReplenishmentSuggestionDto"][];
                        "text/json": components["schemas"]["ReplenishmentSuggestionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Replenishment/warehouse/{warehouseId}/item/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get replenishment suggestion for a single item */
        get: {
            parameters: {
                query?: {
                    horizonDays?: number;
                };
                header?: never;
                path: {
                    warehouseId: number;
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suggestion returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReplenishmentSuggestionDto"];
                        "application/json": components["schemas"]["ReplenishmentSuggestionDto"];
                        "text/json": components["schemas"]["ReplenishmentSuggestionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all roles
         * @description Returns a list of all roles along with their associated permissions.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Roles retrieved successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDto"][];
                        "application/json": components["schemas"]["RoleDto"][];
                        "text/json": components["schemas"]["RoleDto"][];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a new role
         * @description Creates a role with a name, optional description, and an initial list of permissions.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRoleRequest"];
                    "text/json": components["schemas"]["CreateRoleRequest"];
                    "application/*+json": components["schemas"]["CreateRoleRequest"];
                };
            };
            responses: {
                /** @description Role created successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDto"];
                        "application/json": components["schemas"]["RoleDto"];
                        "text/json": components["schemas"]["RoleDto"];
                    };
                };
                /** @description Role already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Role/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get role by ID
         * @description Returns a single role with all assigned permissions.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDto"];
                        "application/json": components["schemas"]["RoleDto"];
                        "text/json": components["schemas"]["RoleDto"];
                    };
                };
                /** @description Role not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a role
         * @description Deletes a role only if it is not assigned to any users. Removes connections to associated permissions automatically.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role deleted successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Success"];
                        "application/json": components["schemas"]["Success"];
                        "text/json": components["schemas"]["Success"];
                    };
                };
                /** @description Role not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Role is assigned to one or more users. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Role/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update role permissions
         * @description Replaces all permissions assigned to a role with a new list of permission keys.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRolePermissionsRequest"];
                    "text/json": components["schemas"]["UpdateRolePermissionsRequest"];
                    "application/*+json": components["schemas"]["UpdateRolePermissionsRequest"];
                };
            };
            responses: {
                /** @description Role permissions updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoleDto"];
                        "application/json": components["schemas"]["RoleDto"];
                        "text/json": components["schemas"]["RoleDto"];
                    };
                };
                /** @description Role not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/SalesOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new sales order */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSalesOrderRequest"];
                    "text/json": components["schemas"]["CreateSalesOrderRequest"];
                    "application/*+json": components["schemas"]["CreateSalesOrderRequest"];
                };
            };
            responses: {
                /** @description Sales order created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesOrderDto"];
                        "application/json": components["schemas"]["SalesOrderDto"];
                        "text/json": components["schemas"]["SalesOrderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/SalesOrder/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales order by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales order returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesOrderDto"];
                        "application/json": components["schemas"]["SalesOrderDto"];
                        "text/json": components["schemas"]["SalesOrderDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/SalesOrder/{id}/allocate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Allocate a sales order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales order allocated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesOrderDto"];
                        "application/json": components["schemas"]["SalesOrderDto"];
                        "text/json": components["schemas"]["SalesOrderDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/SalesOrder/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cancel a sales order */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales order cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/SalesOrder/warehouse/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales orders for a warehouse */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales orders returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesOrderDto"][];
                        "application/json": components["schemas"]["SalesOrderDto"][];
                        "text/json": components["schemas"]["SalesOrderDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Shipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create shipment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateShipmentRequest"];
                    "text/json": components["schemas"]["CreateShipmentRequest"];
                    "application/*+json": components["schemas"]["CreateShipmentRequest"];
                };
            };
            responses: {
                /** @description Shipment created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShipmentDto"];
                        "application/json": components["schemas"]["ShipmentDto"];
                        "text/json": components["schemas"]["ShipmentDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Shipment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shipment returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShipmentDto"];
                        "application/json": components["schemas"]["ShipmentDto"];
                        "text/json": components["schemas"]["ShipmentDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Shipment/warehouse/{warehouseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get shipments for warehouse */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    warehouseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shipments returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ShipmentDto"][];
                        "application/json": components["schemas"]["ShipmentDto"][];
                        "text/json": components["schemas"]["ShipmentDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/UnitOfMeasure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all unit of measures
         * @description Returns all unit of measures in the system.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of unit of measures returned successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitOfMeasureDto"][];
                        "application/json": components["schemas"]["UnitOfMeasureDto"][];
                        "text/json": components["schemas"]["UnitOfMeasureDto"][];
                    };
                };
                /** @description No unit of measures found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/UnitOfMeasure/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unit of measure by ID
         * @description Returns a unit of measure with the specified ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unit of measure found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnitOfMeasureDto"];
                        "application/json": components["schemas"]["UnitOfMeasureDto"];
                        "text/json": components["schemas"]["UnitOfMeasureDto"];
                    };
                };
                /** @description Unit of measure not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/User": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all users
         * @description Returns all users along with their assigned roles their permissions and allowed warehouses.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users retrieved successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"][];
                        "application/json": components["schemas"]["UserDto"][];
                        "text/json": components["schemas"]["UserDto"][];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/User/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user by ID
         * @description Returns the user with full role, permissions and warehouse data.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description User not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Deletes the specified user and removes all related role, warehouse, and refresh-token associations.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Success"];
                        "application/json": components["schemas"]["Success"];
                        "text/json": components["schemas"]["Success"];
                    };
                };
                /** @description You do not have permission to delete users. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/User/{id}/active-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Activate or deactivate a user */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserActiveStatusRequest"];
                    "text/json": components["schemas"]["UpdateUserActiveStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateUserActiveStatusRequest"];
                };
            };
            responses: {
                /** @description User status updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description User not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/User/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update user roles
         * @description Replaces the user's assigned roles with the specified list of role IDs.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRolesRequest"];
                    "text/json": components["schemas"]["UpdateUserRolesRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRolesRequest"];
                };
            };
            responses: {
                /** @description User roles updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description User not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/User/{id}/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update user warehouse access
         * @description Assigns the user access to the specified warehouse IDs.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateUserWarehousesRequest"];
                    "text/json": components["schemas"]["UpdateUserWarehousesRequest"];
                    "application/*+json": components["schemas"]["UpdateUserWarehousesRequest"];
                };
            };
            responses: {
                /** @description User warehouse access updated successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description User not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Warehouse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all warehouses
         * @description Returns all warehouses configured in the Magna WMS system.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of warehouses. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"][];
                        "application/json": components["schemas"]["WarehouseDto"][];
                        "text/json": components["schemas"]["WarehouseDto"][];
                    };
                };
                /** @description No warehouses available. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new warehouse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateWarehouseRequest"];
                    "text/json": components["schemas"]["CreateWarehouseRequest"];
                    "application/*+json": components["schemas"]["CreateWarehouseRequest"];
                };
            };
            responses: {
                /** @description Warehouse created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Warehouse/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get warehouse by ID
         * @description Returns a specific warehouse by its unique identifier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Warehouse found. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
                /** @description Warehouse not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update an existing warehouse */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateWarehouseRequest"];
                    "text/json": components["schemas"]["UpdateWarehouseRequest"];
                    "application/*+json": components["schemas"]["UpdateWarehouseRequest"];
                };
            };
            responses: {
                /** @description Warehouse updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
                /** @description Warehouse not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Warehouse/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate warehouse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Warehouse activated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
                /** @description Warehouse not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Warehouse/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate warehouse */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Warehouse deactivated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WarehouseDto"];
                        "application/json": components["schemas"]["WarehouseDto"];
                        "text/json": components["schemas"]["WarehouseDto"];
                    };
                };
                /** @description Warehouse not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreatePutawayTaskRequest: {
            /** Format: int64 */
            receiptId?: number;
            /** Format: int64 */
            receiptLineId?: number;
            /** Format: double */
            quantityToPutaway?: number;
        };
        CreateReceiptLineRequest: {
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            expectedQty?: number;
        };
        CreateReceiptRequest: {
            /** Format: int64 */
            warehouseId?: number;
            receiptNumber?: string | null;
            externalReference?: string | null;
            /** Format: date-time */
            expectedArrivalDate?: string | null;
            lines?: components["schemas"]["CreateReceiptLineRequest"][] | null;
        };
        CreateRoleRequest: {
            name?: string | null;
            description?: string | null;
            permissionKeys?: string[] | null;
        };
        CreateSalesOrderLineRequest: {
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityOrdered?: number;
        };
        CreateSalesOrderRequest: {
            /** Format: int64 */
            warehouseId?: number;
            orderNumber?: string | null;
            customerName?: string | null;
            lines?: components["schemas"]["CreateSalesOrderLineRequest"][] | null;
        };
        CreateShipmentRequest: {
            /** Format: int64 */
            salesOrderId?: number;
            shipmentNumber?: string | null;
            carrier?: string | null;
            trackingNumber?: string | null;
            lines?: components["schemas"]["ShipmentLineRequest"][] | null;
        };
        CreateWarehouseRequest: {
            code?: string | null;
            name?: string | null;
            timezone?: string | null;
        };
        ExecutePutawayRequest: {
            /** Format: double */
            quantity?: number;
            /** Format: int64 */
            destinationLocationId?: number;
        };
        ForecastPointDto: {
            /** Format: date-time */
            forecastDateUtc?: string;
            /** Format: double */
            quantity?: number;
        };
        ForecastSeriesDto: {
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: date-time */
            generatedUtc?: string;
            /** Format: int32 */
            horizonDays?: number;
            modelInfo?: string | null;
            points?: components["schemas"]["ForecastPointDto"][] | null;
        };
        InventoryDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            locationId?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityOnHand?: number;
            /** Format: double */
            quantityAllocated?: number;
            /** Format: double */
            quantityAvailable?: number;
        };
        InventoryLedgerEntryDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            locationId?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: date-time */
            timestampUtc?: string;
            /** Format: double */
            quantityChange?: number;
            /** Format: double */
            resultingQuantityOnHand?: number;
            movementType?: string | null;
            referenceType?: string | null;
            referenceNumber?: string | null;
        };
        ItemDto: {
            /** Format: int64 */
            itemId?: number;
            sku?: string | null;
            name?: string | null;
            /** Format: int64 */
            unitOfMeasureId?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
        };
        LocationDto: {
            /** Format: int64 */
            locationId?: number;
            /** Format: int64 */
            warehouseId?: number;
            code?: string | null;
            type?: string | null;
            /** Format: int32 */
            maxQty?: number;
            isActive?: boolean;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        LoginResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string | null;
        };
        PermissionDto: {
            /** Format: int64 */
            id?: number;
            key?: string | null;
            description?: string | null;
        };
        PickItemRequest: {
            /** Format: double */
            quantityPicked?: number;
        };
        PickTaskDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            salesOrderId?: number;
            status?: string | null;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
            /** Format: int64 */
            createdByUserId?: number;
            /** Format: int64 */
            completedByUserId?: number | null;
            /** Format: date-time */
            completedUtc?: string | null;
            lines?: components["schemas"]["PickTaskLineDto"][] | null;
        };
        PickTaskLineDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: int64 */
            locationId?: number;
            /** Format: double */
            quantityToPick?: number;
            /** Format: double */
            quantityPicked?: number;
            isCompleted?: boolean;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        PutawayTaskDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            receiptId?: number;
            /** Format: int64 */
            receiptLineId?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityToPutaway?: number;
            /** Format: double */
            quantityCompleted?: number;
            status?: string | null;
            /** Format: int64 */
            createdByUserId?: number;
            /** Format: int64 */
            completedByUserId?: number | null;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            completedUtc?: string | null;
        };
        ReceiptDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            receiptNumber?: string | null;
            externalReference?: string | null;
            /** Format: date-time */
            expectedArrivalDate?: string | null;
            status?: string | null;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            closedUtc?: string | null;
            /** Format: int64 */
            createdByUserId?: number;
            /** Format: int64 */
            receivedByUserId?: number | null;
            lines?: components["schemas"]["ReceiptLineDto"][] | null;
        };
        ReceiptLineDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            itemSku?: string | null;
            itemName?: string | null;
            unitOfMeasure?: string | null;
            /** Format: double */
            expectedQty?: number;
            /** Format: double */
            receivedQty?: number;
            /** Format: int64 */
            toLocationId?: number | null;
            notes?: string | null;
            isFullyReceived?: boolean;
        };
        ReceiveReceiptLineRequest: {
            /** Format: double */
            quantity?: number;
            /** Format: int64 */
            toLocationId?: number;
            notes?: string | null;
        };
        RegisterCommand: {
            email?: string | null;
            password?: string | null;
        };
        RegisterResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string | null;
        };
        ReplenishmentSuggestionDto: {
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityAvailable?: number;
            /** Format: double */
            forecastQtyLeadTime?: number;
            /** Format: double */
            safetyStock?: number;
            /** Format: double */
            reorderPoint?: number;
            /** Format: double */
            suggestedOrderQty?: number;
        };
        RoleDto: {
            /** Format: int64 */
            id?: number;
            name?: string | null;
            description?: string | null;
            permissions?: string[] | null;
        };
        SalesOrderDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            orderNumber?: string | null;
            customerName?: string | null;
            status?: string | null;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
            lines?: components["schemas"]["SalesOrderLineDto"][] | null;
        };
        SalesOrderLineDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityOrdered?: number;
            /** Format: double */
            quantityAllocated?: number;
            /** Format: double */
            quantityPicked?: number;
            isFullyAllocated?: boolean;
            isFullyPicked?: boolean;
        };
        ShipmentDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int64 */
            salesOrderId?: number;
            shipmentNumber?: string | null;
            carrier?: string | null;
            trackingNumber?: string | null;
            /** Format: int64 */
            shippedByUserId?: number;
            /** Format: date-time */
            shippedUtc?: string;
            lines?: components["schemas"]["ShipmentLineDto"][] | null;
        };
        ShipmentLineDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantityShipped?: number;
        };
        ShipmentLineRequest: {
            /** Format: int64 */
            itemId?: number;
            /** Format: double */
            quantity?: number;
        };
        Success: {
            status?: string | null;
        };
        TrainForecastResultDto: {
            /** Format: int64 */
            warehouseId?: number;
            /** Format: int32 */
            itemsConsidered?: number;
            /** Format: int32 */
            itemsForecasted?: number;
            /** Format: int32 */
            itemsSkippedInsufficientHistory?: number;
        };
        UnitOfMeasureDto: {
            /** Format: int64 */
            unitOfMeasureId?: number;
            symbol?: string | null;
            name?: string | null;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
        };
        UpdateRolePermissionsRequest: {
            permissionKeys?: string[] | null;
        };
        UpdateUserActiveStatusRequest: {
            isActive?: boolean;
        };
        UpdateUserRolesRequest: {
            roleIds?: number[] | null;
        };
        UpdateUserWarehousesRequest: {
            warehouseIds?: number[] | null;
        };
        UpdateWarehouseRequest: {
            name?: string | null;
            timezone?: string | null;
        };
        UserDto: {
            /** Format: int64 */
            id?: number;
            email?: string | null;
            isActive?: boolean;
            roles?: string[] | null;
            warehouseIds?: number[] | null;
            permissions?: string[] | null;
        };
        WarehouseDto: {
            /** Format: int64 */
            id?: number;
            code?: string | null;
            name?: string | null;
            timeZone?: string | null;
            isActive?: boolean;
            /** Format: date-time */
            createdUtc?: string;
            /** Format: date-time */
            updatedUtc?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
